import { Employee, Service } from "./types";

export const SERVICES: Service[] = [
  { id: "blowout", name: "سشوار الشعر", price: 15000 },
  { id: "cut", name: "قص وتصفيف الشعر", price: 20000 },
  { id: "color", name: "صبغ الشعر", price: 45000 },
  { id: "highlights", name: "خصل ملونة", price: 60000 },
  { id: "treatment", name: "علاج كيراتين", price: 80000 },
  { id: "manicure", name: "مانيكير", price: 12000 },
  { id: "pedicure", name: "باديكير", price: 15000 },
  { id: "facial", name: "تنظيف بشرة", price: 30000 },
  { id: "makeup", name: "مكياج", price: 50000 },
  { id: "brows", name: "تشذيب الحواجب", price: 10000 },
  { id: "wax", name: "إزالة الشعر بالشمع", price: 18000 },
  { id: "henna", name: "نقش حناء", price: 25000 },
  { id: "lashes", name: "رفع الرموش", price: 35000 },
  { id: "style", name: "تسريحة مناسبات", price: 40000 },
  { id: "spa", name: "سبا فروة الرأس", price: 22000 },
];

export const EMPLOYEES: Employee[] = [
  { id: "e1", name: "Alaa" },
  { id: "e2", name: "Sara" },
  { id: "e3", name: "Noor" },
  { id: "e4", name: "Lana" },
  { id: "e5", name: "Zahra" },
  { id: "e6", name: "Mira" },
  { id: "e7", name: "Huda" },
  { id: "e8", name: "Rasha" },
  { id: "e9", name: "Dalia" },
  { id: "e10", name: "Farah" },
  { id: "e11", name: "Aya" },
  { id: "e12", name: "Hanan" },
  { id: "e13", name: "Reem" },
  { id: "e14", name: "Rana" },
  { id: "e15", name: "Laila" },
  { id: "e16", name: "Noorhan" },
  { id: "e17", name: "Bushra" },
  { id: "e18", name: "Marwa" },
  { id: "e19", name: "Heba" },
  { id: "e20", name: "Rahma" },
  { id: "e21", name: "Yasmine" },
  { id: "e22", name: "Salma" },
  { id: "e23", name: "Dina" },
  { id: "e24", name: "Amal" },
];
